version: "3.9"

services:
  server:
    env_file:
      - .env
    image: python:3.9
    working_dir: /mnt
    volumes:
      - .:/mnt
    depends_on:
      - db
      - redis
    ports:
      - 3000:3000
    command: python src/server.py

  db:
    image: postgres
    container_name: postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: db
    restart: unless-stopped
    volumes:
      - postgres-vol:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning
    volumes:
      - redis:/var/lib/redis/data

  worker:
    env_file:
      - .env
    image: python:3.9
    working_dir: /mnt
    volumes:
      - .:/mnt
    depends_on:
      - redis
    command: python -m celery --app src.server worker --loglevel=DEBUG --logfile=celery.log

  testserver:
    env_file: .env
    image: python:3.9
    working_dir: /mnt
    volumes:
      - postgres-test-vol:/var/lib/postgresql/data
    depends_on:
      - testdb
    ports:
      - 5053:5053
    environment:
      APPLICATION_PORT: 5053
      APPLICATION_DB_CONTAINER: testdb
    command: python -m pytest test/

  testdb:
    image: postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: db

volumes:
  postgres-vol:
  postgres-test-vol:
  redis:


