from .home import HOME_BLUEPRINT
from .authentication import AUTHENTICATION_BLUEPRINT
from .products import PRODUCTS_BLUEPRINT
from .universal import UNIVERSAL_BLUEPRINT
from .cart import CART_BLUEPRINT
from .orders import ORDERS_BLUEPRINT
from .profile import PROFILE_BLUEPRINT
from .category import CATEGORY_BLUEPRINT
from .shipping_price import SHIPPING_BLUEPRINT
from .brand import BRAND_BLUEPRINT