"""empty message

Revision ID: 2022d2e27784
Revises: 76ee44fe0942
Create Date: 2022-11-05 06:54:08.306207

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '2022d2e27784'
down_revision = '76ee44fe0942'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_addresses')
    op.add_column('users', sa.Column('address_name', sa.String(length=300), nullable=True))
    op.add_column('users', sa.Column('address', sa.String(length=300), nullable=True))
    op.add_column('users', sa.Column('city', sa.String(length=300), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'city')
    op.drop_column('users', 'address')
    op.drop_column('users', 'address_name')
    op.create_table('user_addresses',
    sa.Column('id', postgresql.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', postgresql.UUID(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=300), autoincrement=False, nullable=False),
    sa.Column('phone_number', sa.VARCHAR(length=300), autoincrement=False, nullable=True),
    sa.Column('address', sa.VARCHAR(length=300), autoincrement=False, nullable=False),
    sa.Column('city', sa.VARCHAR(length=300), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('deleted_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='user_addresses_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='user_addresses_pkey')
    )
    # ### end Alembic commands ###
