"""empty message

Revision ID: 76ee44fe0942
Revises: adfb309e7f3b
Create Date: 2022-10-29 16:09:50.508265

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '76ee44fe0942'
down_revision = 'adfb309e7f3b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('categories', 'image')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categories', sa.Column('image', sa.VARCHAR(length=300), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
