"""empty message

Revision ID: 85c7ab8a87f4
Revises: e4585390a341
Create Date: 2022-10-26 05:57:16.566569

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '85c7ab8a87f4'
down_revision = 'e4585390a341'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product_images', 'created_at')
    op.drop_column('product_images', 'deleted_at')
    op.create_unique_constraint(None, 'products', ['title', 'category_id', 'condition'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'products', type_='unique')
    op.add_column('product_images', sa.Column('deleted_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('product_images', sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
